### PR TITLE
Maven enhancements

### PR DESCRIPTION
**Pull request by sgdc3**

### CODE REVIEW

**Comment by sgdc3** [comment]
@lenis0012 It should be fine now ;)

**Comment by sgdc3** [comment]
My jenkins setup:

```
Pre Steps:
  Execute shell:
    mvn clean -B
Build:
  Goals and options:
    install javadoc:javadoc -B -P bukkit
Post Steps:
  Run only if build succeeds [x]
  Execute shell:
    mvn package -B -P spigot -DskipTests
Actions after the build:
  Archive artifacts:
    target/LoginSecurity*.jar
```

**Comment by sgdc3** [comment]
Ok tested on my jenkins, it works ;)

**Comment by sgdc3** [comment]
http://ci.xephi.fr/job/LoginSecurity-2/

**Comment by sgdc3** [comment]
There is only 1 maven artifact stored, it doesn't include any shaded libraries

**Comment by lenis0012** [comment]
So when you run this with bukkit & spigot profile it works?

I thought you said you have to use modules o.0
how did you fix it

btw, thank you so much @sgdc3 :)

**Comment by sgdc3** [comment]
you need to run the command 2 times
modules are cool but complicated, it was useless to do it only to have 2 jars

**Comment by lenis0012** [comment]
@sgdc3 but this does register in the maven repo? :)

**Comment by sgdc3** [comment]
It install in the repo only the non shaded jar, as maven is designed

**Pull request merged**
