### PR TITLE
Fixed #241 restore MySQL support on newer MC versions

### LINKED ISSUE #241: Problem with mysql
Hello. When i trying connect to mysql, plugin crashes.

### PR DESCRIPTION
**Pull request by LemADEC**
Fixing a boot issue on recent version of Minecraft due to obsolete dependencies.
Removing clutter

### CODE REVIEW

**Comment by lenis0012** [comment]
this would break 1.8-1.15 compatability no?

**Comment by LemADEC** [comment]
> this would break 1.8-1.15 compatability no?

yes, the dependencies aren't backward compatible, so users of older version of Minecraft will have to rely on previous versions of the plugin.

**Comment by lenis0012** [comment]
fair enough. I will merge it in.

**Comment by lenis0012** [comment]
@LemADEC Note, the updater module is not "broken" you just have to pick an implementation using -Pspigot or -Pbukkit

**Pull request merged**
