### PR TITLE
Add links

### PR DESCRIPTION
**Pull request by Tzzzt123**
I added links to show users where they can find the plugin!

### CODE REVIEW

**Comment by lenis0012** [comment]
add build server?

**Comment by Tzzzt123** [comment]
the links as Spigotmc.org or dev.bukkit.com or mods.curse.com

**Comment by Tzzzt123** [comment]
Lol
===

**Comment by lenis0012** [comment]
@Tzzzt123 the builder server...
ci.lenis0012.com/job/LoginSecurity%202

**Comment by Tzzzt123** [comment]
i meant for server owners to know where they can download the ressource

**Comment by Tzzzt123** [comment]
no, not the build server! the Websites to download the plugin as it is (SPIGOT MC, BUKKITDEV, CURSEMODS)

**Comment by lenis0012** [comment]
You can also download it through the build server. So please add it

**Comment by sgdc3** [comment]
Lol idk what to say xD

**Comment by lenis0012** [comment]
Ill make some manual changes

**Comment by Tzzzt123** [comment]
OK thanks

**Comment by Tzzzt123** [comment]
Ok i will

2016-07-12 18:42 GMT+02:00 lenis0012 <notifications@github.com>:

**Pull request merged**
